### ISSUE TITLE
프로젝트 셋업

### ISSUE THREAD

**Issue by IceMelon404** [depromeet/Archive_Backend#1]
1.  **gitignore 추가 (gitignore.io 이용 권장)**
2.  **maven dependency 설정**

  _스프링 부트_
  - web 
  - security & oauth2 client ( 로그인 기능 구현 여부에 따라)

  _테스팅_
  - junit5
  - mockito
  - RestAssured

  _유틸_
  - lombok

원래 데이터 액세스 계층에 JPA 를 쓰기로 했었는데, 
기능 요구사항이 조금 간단해질 것 같아 다시 의논해보아도 좋을 것 같습니다.
데이터베이스, 캐시로는 무엇을 쓸지 정해진 후에 관련 의존성도 추가해야 합니다.

**Comment by KimDoubleB** [comment]
DB: RDS (MySQL) 사용

**Comment by IceMelon404** [comment]
로컬에서 테스트할 때는 H2 사용

**Comment by IceMelon404** [comment]
jdk 11 사용

**Comment by KimDoubleB** [comment]
![app-store](https://user-images.githubusercontent.com/37873745/162962632-65e08984-47e8-4905-bef1-4de2408ff430.png)
![instagram](https://user-images.githubusercontent.com/37873745/162962649-d1482a3b-0d37-4013-a3d0-283b95d4280f.png)
![mail](https://user-images.githubusercontent.com/37873745/162962656-520a14f1-61fd-4a43-b655-02de86e72ed5.png)
